### ISSUE TITLE
Refine identifier matching during plugin search

### ISSUE THREAD

**Issue by j-o** [cginternals/cppexpose#34]
Currently, `ComponentManager::scanPlugins` checks if the given identifier can be found anywhere in a library's path. This may lead to false positives, e.g. searching for "ui" plugins will find any library in the "build" folder...

I suggest to
 - Limit matching to the base file name, not the entire path
 - Use a regular expression to match the entire base file name instead of a substring that can occur anywhere

**Comment by sbusch42** [comment]
The matching is now limited to the base filename, and only suffixes are considered. In gloperate we for example search for "-plugins" now, or "-plugins-debug" on debug builds. This way, debug and release plugins should be separated.
